// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using System.Linq;
using MyImdbLibrary;

namespace ImdbMacApp
{
    public partial class ViewSignIn : NSViewController
    {
        private DatabaseManager DbManager { get; set; }
        private User MainUser { get; set; }

        public ViewSignIn(IntPtr handle) : base(handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            DbManager = new DatabaseManager();
            DbManager.LoadEnumerations();
        }

        public void LoadEmailAddressAfterSignUpAndDisableButton(string email)
        {
            if (email.Any())
            {
                InputEmail.StringValue = email;
                InputPassword.StringValue = "";
                SignUpButton.Enabled = false;
            }
        }

        public void ClearFieldsAfterSignOut()
        {
            InputEmail.StringValue = "";
            InputPassword.StringValue = "";
        }

        private void ClearInputFields()
        {
            InputEmail.StringValue = "";
            InputPassword.StringValue = "";
        }

        private void AlertMessage(string message, string title)
        {
            var alert = new NSAlert()
            {
                AlertStyle = NSAlertStyle.Informational,
                InformativeText = message,
                MessageText = title,
            };
            alert.AddButton("Ok");
            alert.BeginSheet(View.Window);
        }

        partial void SignInButton_Clicked(NSObject sender)
        {
            string Email = InputEmail.StringValue;
            string Password = InputPassword.StringValue;

            if (Email.Any() && Password.Any())
            {
                if (DatabaseManager.IsValidEmail(Email))
                {
                    (bool, bool, User) result = DbManager.CheckIfUserIsValid(Email, Password);
                    if (result.Item1 && result.Item2)
                    {
                        MainUser = result.Item3;
                        PerformSegue("LaunchMainWindow", this);
                    }
                    else if (result.Item1)
                    {
                        AlertMessage("Please enter the correct password.", "Incorrect Password!");
                        InputPassword.StringValue = "";
                    }
                    else
                    {
                        AlertMessage("Please enter the correct email address.", "User does not exist!");
                        ClearInputFields();
                    }
                }
                else AlertMessage("Please enter a valid email address.", "Invalid Email!");
            }
            else AlertMessage("Please enter the email address and password.", "Enter user credentials!");
        }

        [Export("prepareForSegue:sender:")]
        public override void PrepareForSegue(NSStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);
            switch (segue.Identifier)
            {
                case "LaunchSignUpWindow":
                    {
                        ViewSignUp target = segue.DestinationController as ViewSignUp;
                        target.DbManager = DbManager;
                        target.SignInView = this;
                    }
                    break;
                case "LaunchMainWindow":
                    {
                        ViewController target = segue.DestinationController as ViewController;
                        target.DbManager = DbManager;
                        target.MainUser = MainUser;
                        target.SignInView = this;
                    }
                    break;
            }
        }
    }
}
