// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;

namespace ImdbMacApp
{
	public partial class ViewMovieStory : NSViewController
	{
        public string MovieStory { get; set; }

        public ViewMovieStory (IntPtr handle) : base (handle) { }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            MovieStoryTxt.StringValue = MovieStory;
        }
    }
}
