// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using MyImdbLibrary;
using System.Linq;

namespace ImdbMacApp
{
    public partial class ViewProfile : NSViewController
    {
        public ViewController MainView { get; set; }
        public DatabaseManager DbManager { get; set; }
        public User MainUser { get; set; }

        public ViewProfile(IntPtr handle) : base(handle) { }

        public override void ViewDidAppear()
        {
            base.ViewDidAppear();

            FillForm();
        }

        private void FillForm()
        {
            InputFirstName.StringValue = MainUser.FirstName;
            InputLastName.StringValue = MainUser.LastName;
            InputEmail.StringValue = MainUser.Email;
            InputApiKey.StringValue = MainUser.OmdbApiKey;

            LoadCountry();
        }

        private void LoadCountry()
        {
            InputCountry.UsesDataSource = true;
            InputCountry.DataSource = new DataSource(DbManager.countriesNames);

            string country_name = DbManager.countriesNamesAndCodes.FirstOrDefault(c => c.Id == MainUser.Country).Name;
            InputCountry.SelectItem(DbManager.countriesNames.IndexOf(country_name));
        }

        private bool CheckIfFormIsFilled()
        {
            if (!InputFirstName.StringValue.Any())  return false;
            if (!InputLastName.StringValue.Any())   return false;
            if (!InputEmail.StringValue.Any())      return false;
            if (!InputApiKey.StringValue.Any())     return false;
            return true;
        }

        public void AlertMessage(string message, string title)
        {
            var alert = new NSAlert()
            {
                AlertStyle = NSAlertStyle.Informational,
                InformativeText = message,
                MessageText = title,
            };
            alert.AddButton("Ok");
            alert.BeginSheet(View.Window);
        }

        partial void ConfirmButton_Clicked(NSObject sender)
        {
            if (CheckIfFormIsFilled())
            {
                string FirstName = InputFirstName.StringValue;
                string LastName = InputLastName.StringValue;
                string Email = InputEmail.StringValue;
                string OmdbApiKey = InputApiKey.StringValue;
                int country_id = DbManager.countriesNamesAndCodes.FirstOrDefault(c => c.Name == InputCountry.StringValue).Id;
                string Password1 = InputPassword1.StringValue;
                string Password2 = InputPassword2.StringValue;

                if (DatabaseManager.IsValidEmail(Email))
                {
                    if (DbManager.CheckIfEmailAddressIsFree(Email) || (MainUser.Email == Email))
                    {
                        // User wants to change password:
                        if (Password1.Any())
                        {
                            if (Password1.Length == 8)
                            {
                                if (Password1 == Password2)
                                {
                                    UpdateUserAndCloseView(FirstName, LastName, Email, country_id, OmdbApiKey);
                                }
                                else
                                {
                                    AlertMessage("Please re-enter the same password if you want to change it!", "Invalid Password!");
                                    InputPassword2.StringValue = "";
                                }
                            }
                            else
                            {
                                AlertMessage("Please enter an 8 character password if you want to change your current password!", "Invalid Password!");
                                InputPassword1.StringValue = "";
                                InputPassword2.StringValue = "";
                            }
                        }
                        // User does not want to change the password:
                        else
                        {
                            UpdateUserAndCloseView(FirstName, LastName, Email, country_id, OmdbApiKey);
                        }
                    }
                    else AlertMessage("Email address is already used!", "Invalid Email!");
                }
                else AlertMessage("Please enter a valid email address.", "Invalid Email!");
            }
            else AlertMessage("Please fill all the fields.", "Unsufficient!");
        }

        private void UpdateUserAndCloseView(string FirstName, string LastName, string Email, int country_id, string OmdbApiKey)
        {
            MainUser.FirstName = FirstName;
            MainUser.LastName = LastName;
            MainUser.Email = Email;
            MainUser.Country = country_id;
            MainUser.OmdbApiKey = OmdbApiKey;

            DbManager.UpdateUser(MainUser);
            DismissViewController(this);
            MainView.AlertMessage("Your profile has been successfully updated!", "Profile updated!");
        }

        partial void CancelButton_Clicked(NSObject sender)
        {
            DismissViewController(this);
        }
    }
}
