// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;
using MyImdbLibrary;

namespace ImdbMacApp
{
	public partial class ViewImdbOnline : NSViewController
	{
		public ViewImdbOnline (IntPtr handle) : base (handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var url = new NSUrl(ConstAndParams.ImdbWebsite);
            var request = new NSUrlRequest(url);
            ImdbWebView.LoadRequest(request);
        }
    }
}
