// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ImdbMacApp
{
	public partial class ViewYouTube : NSViewController
	{
        public string MovieUrl { get; set; }

        public ViewYouTube (IntPtr handle) : base (handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var url = new NSUrl(MovieUrl);
            var request = new NSUrlRequest(url);
            YouTubeWebView.LoadRequest(request);
        }
    }
}
